/**
 * Turn data/content.json into the typed module the app imports.
 *
 * content.json is the reviewed output of the writing + fact-check pass; keeping
 * it as data (rather than editing the .ts by hand) means the whole set can be
 * re-audited and regenerated without touching code.
 *
 *   node scripts/build-content.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const areas = JSON.parse(readFileSync(join(root, 'data/areas.json'), 'utf8'))
const raw = JSON.parse(readFileSync(join(root, 'data/content.json'), 'utf8'))
const entries = Array.isArray(raw) ? raw : raw.areas

const byId = new Map(entries.map((e) => [e.id, e]))
const problems = []

for (const a of areas) {
  const e = byId.get(a.id)
  if (!e) {
    problems.push(`missing content for ${a.id} (${a.name})`)
    continue
  }
  for (const f of ['blurb', 'hint', 'fact']) {
    if (!e[f] || typeof e[f] !== 'string' || !e[f].trim()) problems.push(`${a.id}: empty ${f}`)
  }
  // A hint that names its own area is not a hint.
  const bare = a.name.toLowerCase().replace(/[^a-z ]/g, '')
  if (e.hint && e.hint.toLowerCase().includes(bare)) {
    problems.push(`${a.id}: hint leaks the answer ("${e.hint}")`)
  }
  if (e.blurb && /—/.test(e.blurb)) problems.push(`${a.id}: em dash in blurb`)
}

for (const id of byId.keys()) {
  if (!areas.some((a) => a.id === id)) problems.push(`content for unknown id "${id}"`)
}

if (problems.length) {
  console.error('content problems:\n  ' + problems.join('\n  '))
  if (!process.argv.includes('--force')) process.exit(1)
}

const esc = (s) => JSON.stringify(s.trim())

const body = areas
  .map((a) => {
    const e = byId.get(a.id) ?? { blurb: '', hint: '', fact: '' }
    return `  // ${a.name}\n  ${a.id}: {\n    blurb: ${esc(e.blurb ?? '')},\n    hint: ${esc(e.hint ?? '')},\n    fact: ${esc(e.fact ?? '')},\n  },`
  })
  .join('\n')

const ts = `// GENERATED by scripts/build-content.mjs from data/content.json — do not edit by hand.
export type AreaContent = {
  /** shown after the area is found: 2-3 sentences, local voice */
  blurb: string
  /** one short locational clue, never contains the area's own name */
  hint: string
  /** one verifiable fact */
  fact: string
}

export const CONTENT: Record<string, AreaContent> = {
${body}
}
`

writeFileSync(join(root, 'src/data/content.ts'), ts)
console.log(`content.ts  ${areas.length} areas  ${(Buffer.byteLength(ts) / 1024).toFixed(1)} KB`)
